In [1]:
import numpy as np

In [2]:
a=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8]).reshape(3,3)

a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
b=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
for i in b:
    if i%2!=0:
        b[i]=-1

b

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [4]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

a1=np.where(x>y)
a2=np.where(x==y)
        
print(f"Indices where x>y: {a1}")
print(f"Indices where x=y: {a2}")

Indices where x>y: (array([1, 2, 4, 5, 6, 7, 8, 9]),)
Indices where x=y: (array([0]),)


In [5]:
c=np.arange(100).reshape(5,-1)

c[:,:4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

In [6]:
d=np.random.randint(30, 40, 10)
d

array([33, 39, 32, 34, 37, 37, 34, 37, 32, 36])

In [7]:
A=[[1,2,3],
  [4,5,6],
  [7,8,10]]

B=[[7,8,10],
   [4,5,6],
   [1,2,3]]


C=np.array(A)+ np.array(B)
E=np.array(A)- np.array(B)

print(f"Sum C: \n{C}")
print(f"Difference E: \n{E}")

print(f"\nSum of all elements of A: {np.sum(A)}")
print(f"Column sum of B: {np.sum(B,0)}")
print(f"Row sum of C: {np.sum(C,1)}")

D=np.matmul(A, B)
print(f"\nProduct of A and B: D= \n{D}")

print(f"\nSorted elements of C: \n{np.sort(C)}")

print(f"\nTranpose of E is: \n{E.T}")

Sum C: 
[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
Difference E: 
[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]

Sum of all elements of A: 46
Column sum of B: [12 15 19]
Row sum of C: [31 30 31]

Product of A and B: D= 
[[ 18  24  31]
 [ 54  69  88]
 [ 91 116 148]]

Sorted elements of C: 
[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]

Tranpose of E is: 
[[-6  0  6]
 [-6  0  6]
 [-7  0  7]]
